Repository programacion-6/ExpenseTrackerGrupo2, pull requests merged in 2024-09, with the labels that each got.

#1 feat: project initialization
  .gitignore
  ExpenseTrackerGrupo2.csproj
  ExpenseTrackerGrupo2.http
  Program.cs
  Properties/launchSettings.json
  appsettings.Development.json
  appsettings.json
Labels: feature

#2 feat: dockerfile configuration
  Dockerfile
  src/ExpenseTrackerGrupo2/Program.cs
Labels: feature

#6 feat: ID-20/Set-up-CI-Workflows
  .github/pull_request_template.md
  .github/workflows/check-pull-request.yml
Labels: feature

#5 chore: add dapper and swagger
  ExpenseTrackerGrupo2.csproj
Labels: chore

#3 feat: style configuration
  .editorconfig
Labels: feature

#9 chore: resolve CI problems
  .github/workflows/check-pull-request.yml
  .github/workflows/check-push.yml
Labels: hotfix

#10 docs: add folder layers
  src/ExpenseTrackerGrupo2/Api/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Business/ExpenseBusiness.cs
  src/ExpenseTrackerGrupo2/DataAccess/Contexts/ExpenseContext.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/ExpenseEntities.cs
Labels: documentation

#8 docs: add uml initial version
  docs/uml/ExpenseTracker.png
  docs/uml/ExpenseTracker.puml
Labels: documentation, feature

#12 feat: structure of domain entities
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Budget.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Expense.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/ExpenseEntities.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Goal.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Income.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/User.cs
Labels: feature

#13 chore: docker compose creation
  Dockerfile
  docker-compose.yml
Labels: feature

#11 docs: refactor uml packages
  docs/uml/V1/expense-tracker-api.puml
  docs/uml/assets/expense-tracker-v1.png
  docs/uml/assets/expense-tracker-v2.png
  docs/uml/business-logic.puml
  docs/uml/data-access.puml
  docs/uml/data.puml
  docs/uml/infrastructure.puml
  docs/uml/presentation.puml
Labels: documentation

#16 refactor: add attributes to entities according to the UML
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Budget.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Expense.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Goal.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Income.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/User.cs
Labels: feature

#14 docs: improve uml diagram
  docs/uml/assets/expense-tracker-v3.png
  docs/uml/business-logic.puml
  docs/uml/data-access.puml
  docs/uml/data.puml
  docs/uml/infrastructure.puml
  docs/uml/presentation.puml
Labels: documentation

#18 feat: database query and integration
  docker-compose.yml
  src/ExpenseTrackerGrupo2/Persistence/Database/Scripts/init.sql
Labels: feature, chore

#19 feat: implement repositories
  src/ExpenseTrackerGrupo2/Data/IDbConnectionFactory.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/BaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/ExpenseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/IncomeRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IBaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IExpenseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IIncomeRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IUserRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/UserRepository.cs
  src/ExpenseTrackerGrupo2/Utils/StringUtils.cs
Labels: feature

#15 feat: implement services logic
  src/ExpenseTrackerGrupo2/Api/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Business/ExpenseBusiness.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Expenses/ExpenseCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Expenses/ExpenseUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Incomes/IncomeCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Incomes/IncomeUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Users/UserCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Users/UserUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IExpenseService.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IIncomeService.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IUserService.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/DataAccess/Contexts/ExpenseContext.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Budget.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Expense.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Goal.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Income.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/User.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/BaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/ExpenseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/IncomeRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/UserRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IBaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IExpenseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IIncomeRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IUserRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Utils/StringUtils.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/IDbConnectionFactory.cs
Labels: feature

#21 feat: services implementation
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IUserService.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
  src/ExpenseTrackerGrupo2/Services/IncomeService.cs
  src/ExpenseTrackerGrupo2/Services/UserService.cs
Labels: feature

#20 feat: implement database connection
  ExpenseTrackerGrupo2.csproj
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/BaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/ExpenseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/IncomeRepository.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/DbConstants.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/DbInitializer.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/IDbConnectionFactory.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/IUnitOfWork.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/NpgsqlConnectionFactory.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/UnitOfWork.cs
Labels: feature

#25 hotfix: resolve db connection
  Program.cs
  appsettings.json
  docker-compose.yml
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Expenses/ExpenseCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Expenses/ExpenseUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Incomes/IncomeCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Incomes/IncomeUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Users/UserCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Users/UserUpdateRequest.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Budget.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Expense.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Goal.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Income.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/User.cs
  src/ExpenseTrackerGrupo2/DependencyInjection/ServiceCollectionExtensions.cs
  src/ExpenseTrackerGrupo2/Persistence/Database/Scripts/init.sql
  src/ExpenseTrackerGrupo2/Program.cs
  src/ExpenseTrackerGrupo2/RequestPipeline/WebApplicationExtensions.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
  src/ExpenseTrackerGrupo2/Services/IncomeService.cs
Labels: hotfix

#22 feat: add create endpoints
  ExpenseTrackerGrupo2.csproj
  src/ExpenseTrackerGrupo2/Controllers/IncomeController.cs
Labels: feature

#24 feat: add creation endpoints for the Expense
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IExpenseService.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
Labels: feature

#27 fix: set tablename_id in update
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IExpenseService.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IIncomeService.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Controllers/IncomeController.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Income.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/BaseRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IBaseRepository.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
  src/ExpenseTrackerGrupo2/Services/IncomeService.cs
Labels: hotfix

#28 feat: goals implementation
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Expenses/ExpenseUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Goals/GoalUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IGoalService.cs
  src/ExpenseTrackerGrupo2/Controllers/GoalController.cs
  src/ExpenseTrackerGrupo2/Controllers/IncomeController.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Goal.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/GoalRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IGoalRepository.cs
  src/ExpenseTrackerGrupo2/DependencyInjection/ServiceCollectionExtensions.cs
  src/ExpenseTrackerGrupo2/Services/GoalService.cs
Labels: feature

#30 feat: expense insights
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IExpenseService.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
Labels: feature

#31 feat: controller budget management
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetCreateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Mappers/Requests/Budgets/BudgetUpdateRequest.cs
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IBudgetService.cs
  src/ExpenseTrackerGrupo2/Controllers/BudgetController.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/DataAccess/Entities/Budget.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Concretes/BudgetRepository.cs
  src/ExpenseTrackerGrupo2/DataAccess/Repositories/Interfaces/IBudgetRepository.cs
  src/ExpenseTrackerGrupo2/DependencyInjection/ServiceCollectionExtensions.cs
  src/ExpenseTrackerGrupo2/Services/BudgetService.cs
Labels: feature

#35 feat: add most expenses month
  src/ExpenseTrackerGrupo2/Business/Services/Interfaces/IExpenseService.cs
  src/ExpenseTrackerGrupo2/Controllers/ExpenseController.cs
  src/ExpenseTrackerGrupo2/Services/ExpenseService.cs
Labels: feature
